### ISSUE TITLE
Error while launching ImsvGraphVis

### ISSUE THREAD

**Issue by alx** [kwonoh/ImsvGraphVis#2]
Hi,

I'm opening this new issue because the last one has been resolved.

Here is the log when I'm trying to start ImsvGraphVis with the launch options when right-clicking on ImsvGraphVis icon.

I'm not sure what's raising an error, can you have a look ?

Thanks :)

[ImsvGraphVis-backup-2017.10.12-13.17.04.log](https://github.com/VIDILabs/ImsvGraphVis/files/1379119/ImsvGraphVis-backup-2017.10.12-13.17.04.log)

**Comment by kwonoh** [comment]
Hi,

First, can you launch the project from Visual Studio using `Debug - Start Debugging (F5)` or `Debug -
 Start without Debugging (Ctrl + F5)`?

Thank you,
Oh-Hyun

**Comment by alx** [comment]
Thanks, it's launching :)
