### ISSUE TITLE
License

### ISSUE THREAD

**Issue by davidkuhta** [kwonoh/ImsvGraphVis#4]
Hi @kwonoh,

Congrats to you and the team, this is awesome work.

I was wondering if you could confirm the license under which this has been released (and/or update with a **LICENSE.md**)? I'm investigating graph visualization in immersive environments as well (academic context), but would only want to use ImsvGraphVis within the bounds of its authorized use.

Thanks,
David

**Comment by kwonoh** [comment]
Hi @davidkuhta,

Thank you for your interest in this project.
I have added [LICENSE](https://github.com/VIDILabs/ImsvGraphVis/blob/master/LICENSE) (The 3-Clause BSD License) in this repository.

Cheers,
Oh-Hyun
